dependencies {
	compileOnly group: "com.fasterxml.jackson.core", name: "jackson-annotations", version: "2.16.1"
	compileOnly group: "com.liferay", name: "jakarta.ws.rs", version: "3.1.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "78.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "16.6.0"
	compileOnly group: "io.swagger.core.v3", name: "swagger-annotations-jakarta", version: "2.2.28"
	compileOnly group: "jakarta.annotation", name: "jakarta.annotation-api", version: "2.1.1"
	compileOnly group: "jakarta.servlet", name: "jakarta.servlet-api", version: "6.0.0"
	compileOnly group: "jakarta.validation", name: "jakarta.validation-api", version: "3.1.0"
	compileOnly group: "jakarta.xml.bind", name: "jakarta.xml.bind-api", version: "4.0.2"
	compileOnly group: "org.osgi", name: "org.osgi.annotation.versioning", version: "1.1.0"
	compileOnly group: "com.liferay", name: "com.liferay.data.engine.rest.api", version: "32.0.1"
	compileOnly group: "com.liferay", name: "com.liferay.document.library.api", version: "27.0.1"
	compileOnly group: "com.liferay", name: "com.liferay.dynamic.data.mapping.api", version: "35.6.1"
	compileOnly group: "com.liferay", name: "com.liferay.dynamic.data.mapping.form.field.type.api", version: "1.6.1"
	compileOnly group: "com.liferay", name: "com.liferay.headless.admin.user.api", version: "29.5.0"
	compileOnly group: "com.liferay", name: "com.liferay.journal.api", version: "41.0.1"
	compileOnly group: "com.liferay", name: "com.liferay.journal.article.dynamic.data.mapping.form.field.type.api", version: "1.0.6"
	compileOnly group: "com.liferay", name: "com.liferay.layout.dynamic.data.mapping.form.field.type.api", version: "1.0.6"
	compileOnly group: "com.liferay", name: "com.liferay.message.boards.api", version: "28.1.0"
	compileOnly group: "com.liferay", name: "com.liferay.object.api", version: "120.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.portal.odata.api", version: "5.1.0"
	compileOnly group: "com.liferay", name: "com.liferay.portal.search.api", version: "21.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.portal.vulcan.api", version: "48.6.0"
	compileOnly group: "com.liferay", name: "com.liferay.petra.function"
	compileOnly group: "com.liferay", name: "com.liferay.petra.io"
	compileOnly group: "com.liferay", name: "com.liferay.petra.string"
}