dependencies {
	compileOnly group: "com.fasterxml.jackson.core", name: "jackson-annotations", version: "2.18.6"
	compileOnly group: "com.fasterxml.jackson.core", name: "jackson-core", version: "2.18.6"
	compileOnly group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.18.6"
	compileOnly group: "com.liferay", name: "jakarta.ws.rs", version: "3.1.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "org.osgi.service.jaxrs", version: "1.0.0.JAKARTA-LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay.jakarta.portlet", name: "com.liferay.jakarta.portlet-api", version: "4.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.util.taglib", version: "default"
	compileOnly group: "io.swagger.core.v3", name: "swagger-annotations-jakarta", version: "2.2.28"
	compileOnly group: "jakarta.annotation", name: "jakarta.annotation-api", version: "2.1.1"
	compileOnly group: "jakarta.servlet", name: "jakarta.servlet-api", version: "6.0.0"
	compileOnly group: "jakarta.validation", name: "jakarta.validation-api", version: "3.1.0"
	compileOnly group: "org.jsoup", name: "jsoup", version: "1.15.3"
	compileOnly group: "org.osgi", name: "org.osgi.service.component", version: "1.4.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.adaptive.media.api"
	compileOnly group: "com.liferay", name: "com.liferay.adaptive.media.image.api"
	compileOnly group: "com.liferay", name: "com.liferay.asset.api"
	compileOnly group: "com.liferay", name: "com.liferay.asset.display.page.api"
	compileOnly group: "com.liferay", name: "com.liferay.asset.link.api"
	compileOnly group: "com.liferay", name: "com.liferay.asset.list.api"
	compileOnly group: "com.liferay", name: "com.liferay.batch.engine.api"
	compileOnly group: "com.liferay", name: "com.liferay.blogs.api"
	compileOnly group: "com.liferay", name: "com.liferay.client.extension.api"
	compileOnly group: "com.liferay", name: "com.liferay.client.extension.type.api"
	compileOnly group: "com.liferay", name: "com.liferay.data.engine.api"
	compileOnly group: "com.liferay", name: "com.liferay.data.engine.rest.api"
	compileOnly group: "com.liferay", name: "com.liferay.depot.api"
	compileOnly group: "com.liferay", name: "com.liferay.document.library.api"
	compileOnly group: "com.liferay", name: "com.liferay.dynamic.data.lists.api"
	compileOnly group: "com.liferay", name: "com.liferay.dynamic.data.mapping.api"
	compileOnly group: "com.liferay", name: "com.liferay.dynamic.data.mapping.form.field.type.api"
	compileOnly group: "com.liferay", name: "com.liferay.fragment.api"
	compileOnly group: "com.liferay", name: "com.liferay.fragment.entry.processor.api"
	compileOnly group: "com.liferay", name: "com.liferay.friendly.url.api"
	compileOnly group: "com.liferay", name: "com.liferay.headless.admin.user.api"
	compileOnly group: "com.liferay", name: "com.liferay.headless.common.spi"
	compileOnly group: "com.liferay", name: "com.liferay.info.api"
	compileOnly group: "com.liferay", name: "com.liferay.info.list.provider.item.selector.api"
	compileOnly group: "com.liferay", name: "com.liferay.item.selector.criteria.api"
	compileOnly group: "com.liferay", name: "com.liferay.journal.api"
	compileOnly group: "com.liferay", name: "com.liferay.journal.article.dynamic.data.mapping.form.field.type.api"
	compileOnly group: "com.liferay", name: "com.liferay.knowledge.base.api"
	compileOnly group: "com.liferay", name: "com.liferay.layout.api"
	compileOnly group: "com.liferay", name: "com.liferay.layout.display.page.api"
	compileOnly group: "com.liferay", name: "com.liferay.layout.dynamic.data.mapping.form.field.type.api"
	compileOnly group: "com.liferay", name: "com.liferay.layout.page.template.api"
	compileOnly group: "com.liferay", name: "com.liferay.layout.seo.api"
	compileOnly group: "com.liferay", name: "com.liferay.message.boards.api"
	compileOnly group: "com.liferay", name: "com.liferay.object.api"
	compileOnly group: "com.liferay", name: "com.liferay.portal.odata.api"
	compileOnly group: "com.liferay", name: "com.liferay.portal.search.api"
	compileOnly group: "com.liferay", name: "com.liferay.portal.vulcan.api"
	compileOnly group: "com.liferay", name: "com.liferay.segments.api"
	compileOnly group: "com.liferay", name: "com.liferay.site.navigation.api"
	compileOnly group: "com.liferay", name: "com.liferay.style.book.api"
	compileOnly group: "com.liferay", name: "com.liferay.subscription.api"
	compileOnly group: "com.liferay", name: "com.liferay.upload.api"
	compileOnly group: "com.liferay", name: "com.liferay.wiki.api"
	compileOnly group: "com.liferay", name: "com.liferay.osgi.service.tracker.collections"
	compileOnly group: "com.liferay", name: "com.liferay.petra.function"
	compileOnly group: "com.liferay", name: "com.liferay.petra.io"
	compileOnly group: "com.liferay", name: "com.liferay.petra.lang"
	compileOnly group: "com.liferay", name: "com.liferay.petra.sql.dsl.api"
	compileOnly group: "com.liferay", name: "com.liferay.petra.string"
	compileOnly project(":modules:headless-delivery:headless-delivery-api")
}
